### ISSUE TITLE
Erweiterte Strukur für Kategroien / Tags und Labels

### ISSUE THREAD

**Issue by einworB** [einworB/FashionApp#15]
Anlegen logischer Tags für Kleidungsstücke (T-Shirt, Rock, etc) und Outfits (Sommer, Sport, etc).
Implementierung der Möglichkeit für den Nutzer selbst Tags hinzuzfügen

abhängig von #3

**Comment by magnimma** [comment]
Umentscheidung: - Nutzer haben nicht mehr die Möglichkeit selbst Tags anzulegen, da unübersichtlich
- Mögliche Einordnungen: 
  Kategorien(Top,Bottom..), Jahreszeit, Anlass, Farbe
